name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd test; make

    - name: Run1
      run: cd test; ./main | test 1 -eq $(grep -c "\-46406607d-4_6") 

    - name: Run2
      run: cd test; ./main | test 1 -eq $(grep -c "4-60664-6") 

    - name: Run3
      run: cd test; ./main | test 1 -eq $(grep -c "24-65b66407d24-6") 
